-- Migration 018: Seed static ministries and ministry keywords from
-- backend/narrative/ministry_keywords.py::MINISTRY_KEYWORDS.
-- Restores the deterministic canonical-name lookup used by
-- backend/parse/base.py::_get_canonical_ministry. Idempotent.

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Environment and Tourism', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'eco-tourism', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'wildlife', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'hunting', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'concessions', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'mophane', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'parks', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'tourism levy', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'tourism', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'eco tourism', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'national park', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'game reserve', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'safari', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'biodiversity', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'conservation', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'elephant', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'wild life', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Environment and Tourism';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Water and Human Settlement', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'housing', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'bonno', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'waterlogging', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'wetlands', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'oodi', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'water supply', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'water', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'drought', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'settlement', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'human settlement', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'sanitation', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'dam', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'borehole', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Water and Human Settlement';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Minerals and Energy', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'fuel', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'brent crude', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'petroleum', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'debswana', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'meropa resources', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'bpc', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'electricity', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'energy', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'minerals', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'mining', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'coal', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'solar', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'power', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'oil', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'gas', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'diamond', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Minerals and Energy';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Finance', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'vat', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'pension', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'two pot', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'revenue', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'burs', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'tax debt', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'budget', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'tax', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'fiscal', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'treasury', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'pula', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'financial', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'appropriation', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'expenditure', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'fund', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Finance';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Health', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'hospital', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'clinic', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'medicine', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'pharmaceutical', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'nhs', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'disease', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'patient', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'nurse', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'doctor', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'healthcare', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'covid', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'vaccine', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'epidemic', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'health', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Health';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Lands and Agriculture', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'farm', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'farming', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'crop', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'livestock', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'agriculture', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'land', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'arable', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'ranch', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'cattle', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'plough', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'harvest', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'irrigation', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'pastoral', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'temothuo', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Lands and Agriculture';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Local Government and Traditional Affairs', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'council', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Local Government and Traditional Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'municipal', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Local Government and Traditional Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'district', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Local Government and Traditional Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'traditional', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Local Government and Traditional Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'kgosi', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Local Government and Traditional Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'ward', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Local Government and Traditional Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'village development', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Local Government and Traditional Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'community', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Local Government and Traditional Affairs';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Transport and Infrastructure', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'road', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'bridge', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'transport', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'railway', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'airport', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'highway', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'infrastructure', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'bypass', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'construction', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Transport and Infrastructure';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Child Welfare and Basic Education', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'school', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'education', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'student', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'teacher', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'curriculum', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'classroom', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'bursary', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'scholarship', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'literacy', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'primary school', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'secondary school', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Child Welfare and Basic Education';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Trade and Entrepreneurship', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'trade', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'business', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'sme', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'enterprise', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'commerce', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'entrepreneur', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'industry', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'retail', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'export', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Trade and Entrepreneurship';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Labour and Home Affairs', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'labour', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'employment', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'worker', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'union', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'wage', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'immigration', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'passport', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'visa', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'id card', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'omang', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Labour and Home Affairs';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Sports and Arts', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'sport', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Sports and Arts';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'art', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Sports and Arts';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'culture', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Sports and Arts';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'athlete', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Sports and Arts';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'stadium', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Sports and Arts';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'heritage', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Sports and Arts';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'museum', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Sports and Arts';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'gallery', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Sports and Arts';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Justice and Correctional Services', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'court', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'prison', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'correctional', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'justice', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'judge', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'magistrate', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'legal', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'law', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'attorney', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'police', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'prosecution', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'trial', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Justice and Correctional Services';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Communications and Innovation', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'internet', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'digital', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'technology', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'innovation', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'telecom', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'broadband', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'communications', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'data', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'cyber', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'ict', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'botswana television', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'radio', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'broadcasting', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Communications and Innovation';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Higher Education', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'university', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Higher Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'college', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Higher Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'tertiary', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Higher Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'degree', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Higher Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'graduate', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Higher Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'academic', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Higher Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'research', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Higher Education';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'campus', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Higher Education';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('Youth and Gender Affairs', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'youth', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Youth and Gender Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'gender', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Youth and Gender Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'women', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Youth and Gender Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'empowerment', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Youth and Gender Affairs';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'girl child', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'Youth and Gender Affairs';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('International Relations', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'foreign', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'diplomatic', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'embassy', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'international', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'treaty', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'sadc', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'au', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'un', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'african union', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'International Relations';

INSERT OR IGNORE INTO ministries (canonical_name, source_type, first_seen_date, last_seen_date) VALUES ('State President, Defence and Security', 'static_seed', date('now'), date('now'));
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'president', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'defence', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'security', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'military', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'army', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'bdf', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'defense', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'national security', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'intelligence', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'vice president', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
INSERT OR IGNORE INTO ministry_keywords (ministry_id, keyword, weight, source_type) SELECT id, 'state president', 1.0, 'static_seed' FROM ministries WHERE canonical_name = 'State President, Defence and Security';
