"""Model-agnostic knowledge export.

Writes the learned knowledge to plain files any model can read:
  - docs/LEARNED.md (markdown digest, committed to the repo)
  - data/knowledge/learned.json (structured export, runtime artifact)
"""

from __future__ import annotations

import json
import logging
import sqlite3
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from backend.learn.config import get_config
from backend.learn.connection import LearnConnection

logger = logging.getLogger(__name__)


class KnowledgeExporter:
    """Export learned memory and decisions to model-agnostic files."""

    def __init__(self) -> None:
        """Initialize the exporter with the shared connection."""
        self._cfg = get_config()
        self._conn = LearnConnection.get()

    def _memory_rows(self, limit: int) -> list[dict[str, Any]]:
        """Return memory rows ordered by confidence, newest first."""
        try:
            rows = self._conn.execute(
                f"""
                SELECT * FROM {self._cfg.memory_table}
                ORDER BY confidence DESC, created_at DESC
                LIMIT ?
                """,
                (limit,),
            ).fetchall()
            return [dict(r) for r in rows]
        except sqlite3.Error as exc:
            logger.error('Memory export failed: %s', exc)
            return []

    def _decision_rows(self, limit: int) -> list[dict[str, Any]]:
        """Return decision rows, most recent first."""
        try:
            rows = self._conn.execute(
                f"""
                SELECT * FROM {self._cfg.decision_table}
                ORDER BY created_at DESC
                LIMIT ?
                """,
                (limit,),
            ).fetchall()
            return [dict(r) for r in rows]
        except sqlite3.Error as exc:
            logger.error('Decision export failed: %s', exc)
            return []

    def _build_markdown(
        self,
        memories: list[dict[str, Any]],
        decisions: list[dict[str, Any]],
    ) -> str:
        """Build the markdown knowledge digest."""
        lines = [
            '# Learned System Knowledge',
            '',
            'This file is generated by `backend.learn`. It records what the',
            'system has learned from its own data. Any model working on this',
            'codebase may read this file as context.',
            '',
            f'Generated: {datetime.now(UTC).isoformat()}',
            '',
            '## Facts and patterns',
            '',
        ]

        if not memories:
            lines.append('_No knowledge recorded yet. Run `python -m backend.learn.run`._')
            lines.append('')
        else:
            for m in memories:
                category = m.get('category', 'fact')
                key = m.get('key', '')
                value = m.get('value', '')
                source = m.get('source', '')
                lines.append(f'- [{category}] {key}: {value}  _(source: {source})_')
            lines.append('')

        lines.extend(['## Decisions', ''])
        if not decisions:
            lines.append('_No decisions recorded yet._')
            lines.append('')
        else:
            for d in decisions:
                summary = d.get('summary', '')
                made = d.get('decision_made', '')
                outcome = d.get('outcome', 'pending')
                lines.append(f'- [{outcome}] {summary}: {made}')
            lines.append('')

        return '\n'.join(lines)

    def export_markdown(self) -> Path:
        """Write the markdown digest to the configured path.

        Returns:
            Path to the written file.
        """
        memories = self._memory_rows(self._cfg.export_limit)
        decisions = self._decision_rows(self._cfg.export_limit)
        text = self._build_markdown(memories, decisions)
        path = Path(self._cfg.markdown_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8')
        logger.info('Exported markdown digest to %s', path)
        return path

    def export_json(self) -> Path:
        """Write the structured JSON export to the configured path.

        Returns:
            Path to the written file.
        """
        payload = {
            'generated_at': datetime.now(UTC).isoformat(),
            'memories': self._memory_rows(self._cfg.export_limit),
            'decisions': self._decision_rows(self._cfg.export_limit),
        }
        path = Path(self._cfg.json_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2),
            encoding='utf-8',
        )
        logger.info('Exported JSON knowledge to %s', path)
        return path

    def export_all(self) -> dict[str, str]:
        """Write both knowledge artifacts.

        Returns:
            Dict of artifact kind to output path.
        """
        markdown = self.export_markdown()
        json_out = self.export_json()
        return {
            'markdown': str(markdown),
            'json': str(json_out),
        }
